######################################################################
#
# File name : decode_TB_wave.do
# Created on: Tue Jul 19 09:36:34 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
