######################################################################
#
# File name : decode_TB_simulate.do
# Created on: Thu Apr 11 15:15:20 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L blk_mem_gen_v8_4_1 -L fifo_generator_v13_2_1 -L dist_mem_gen_v8_0_12 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.decode_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {decode_TB_wave.do}

view wave
view structure
view signals

do {decode_TB.udo}

run 1000ns
