# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/example_design/encode_exdes.xdc

# IP: ip/encode/encode.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==encode || ORIG_REF_NAME==encode} -quiet] -quiet
