# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param simulator.modelsimInstallPath D:/modelsim/win64
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.cache/wt [current_project]
set_property parent.project_path E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files e:/ldpc/fpga_ldpc/my_code/coe/rom1.coe
add_files e:/ldpc/fpga_ldpc/my_code/coe/rom2.coe
add_files e:/ldpc/fpga_ldpc/my_code/coe/rom3.coe
add_files e:/ldpc/fpga_ldpc/my_code/coe/rom4.coe
read_mem {
  E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/imports/example_design/gt_rom_init_rx.dat
  E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/imports/example_design/gt_rom_init_tx.dat
}
read_verilog -library xil_defaultlib {
  E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/imports/example_design/support/encode_common.v
  E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/imports/example_design/support/encode_common_reset.v
  E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/imports/example_design/encode_gt_frame_gen.v
  E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/imports/example_design/support/encode_gt_usrclk_source.v
  E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/new/encode_p.v
  E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/imports/example_design/support/encode_support.v
  E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/new/fifo_control.v
  E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/new/ldpc_control.v
  E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/imports/example_design/encode_exdes.v
}
read_ip -quiet E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/encode/encode.xci
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/encode/encode.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/encode/encode_ooc.xdc]

read_ip -quiet E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H1/H1.xci
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H1/H1_ooc.xdc]

read_ip -quiet e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H2/H2.xci
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H2/H2_ooc.xdc]

read_ip -quiet e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H3/H3.xci
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H3/H3_ooc.xdc]

read_ip -quiet e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H4/H4.xci
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H4/H4_ooc.xdc]

read_ip -quiet e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/wr_fifo/wr_fifo.xci
set_property used_in_synthesis false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/wr_fifo/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/wr_fifo/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/wr_fifo/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/wr_fifo/wr_fifo_ooc.xdc]

read_ip -quiet e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/rd_fifo/rd_fifo.xci
set_property used_in_synthesis false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/rd_fifo/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/rd_fifo/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/rd_fifo/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/rd_fifo/rd_fifo_ooc.xdc]

read_ip -quiet e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/ila_1/ila_1.xci
set_property used_in_synthesis false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/constrs_1/imports/example_design/encode_exdes.xdc
set_property used_in_implementation false [get_files E:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/constrs_1/imports/example_design/encode_exdes.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top encode_exdes -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef encode_exdes.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file encode_exdes_utilization_synth.rpt -pb encode_exdes_utilization_synth.pb"
