# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_1/H1_1.xci
# IP: The module: 'H1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_1/H1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'H1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_1/H1_1.xci
# IP: The module: 'H1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_1/H1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'H1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
