# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H4/H4.xci
# IP: The module: 'H4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H4/H4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'H4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H4/H4.xci
# IP: The module: 'H4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ldpc_jiaoxue/ldpc_jiaoxue/encode_ex/encode_ex.srcs/sources_1/ip/H4/H4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'H4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
