# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath D:/modelsim/win64
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/ldpc_5_v2_ber_test/test_ldpc.cache/wt [current_project]
set_property parent.project_path E:/ldpc_5_v2_ber_test/test_ldpc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/ldpc_5_v2_ber_test/test_ldpc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_1/coe4_1.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_2/coe4_2.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_3/coe4_3.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_4/coe4_4.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_1/coe1_1.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_2/coe1_2.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_3/coe1_3.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_4/coe1_4.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_1/coe2_1.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_2/coe2_2.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_3/coe2_3.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_4/coe2_4.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_1/coe3_1.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_2/coe3_2.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_3/coe3_3.coe
add_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_4/coe3_4.coe
add_files E:/ldpc_5_v2_ber_test/ber.coe
read_verilog -library xil_defaultlib {
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/decode_code/all_control.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/new/ber_com.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/decode_code/buff.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/example_design/decode_gt_frame_gen.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/decode_code/decode_out.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/example_design/support/decode_support.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/decode_code/error_comp.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/decode_code/error_control.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/decode_code/f_control.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/new/fifo_ber.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/decode_code/find_max.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/new/fn_1.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/new/fn_2.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/new/fn_3.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/new/fn_4.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/decode_code/invert.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/Desktop/rx_clk_common.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/Desktop/rx_clk_common_reset.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/Desktop/rx_clk_gt_usrclk_source.v
  E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/imports/example_design/decode_exdes.v
}
read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ila_1/ila_1.xci
set_property used_in_synthesis false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ten_bit/ten_bit.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ten_bit/ten_bit_board.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ten_bit/ten_bit.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ten_bit/ten_bit_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_1/coe4_1.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_1/coe4_1_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_2/coe4_2.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_2/coe4_2_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_3/coe4_3.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_3/coe4_3_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_4/coe4_4.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/coe4_4/coe4_4_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_1/H1_1.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_1/H1_1_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_2/H1_2.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_2/H1_2_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_3/H1_3.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_3/H1_3_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_4/H1_4.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H1_4/H1_4_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_1/H2_1.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_1/H2_1_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_2/H2_2.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_2/H2_2_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_3/H2_3.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_3/H2_3_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_4/H2_4.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_4/H2_4_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_1/H3_1.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_1/H3_1_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_2/H3_2.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_2/H3_2_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_3/H3_3.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_3/H3_3_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_4/H3_4.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H3_4/H3_4_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/decode/decode.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/decode/decode.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/decode/decode_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/data_pri/data_pri.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/data_pri/data_pri_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_ila/ber_ila.xci
set_property used_in_synthesis false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_ila/ber_ila_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll_board.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_fifo/ber_fifo.xci
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_fifo/ber_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_fifo/ber_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/ber_fifo/ber_fifo_ooc.xdc]

read_ip -quiet E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_ila_1/fifo_ila.xci
set_property used_in_synthesis false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/fifo_ila_1/fifo_ila_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/ldpc_5_v2_ber_test/test_ldpc.srcs/constrs_1/new/decode_exds.xdc
set_property used_in_implementation false [get_files E:/ldpc_5_v2_ber_test/test_ldpc.srcs/constrs_1/new/decode_exds.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top decode_exdes -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef decode_exdes.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file decode_exdes_utilization_synth.rpt -pb decode_exdes_utilization_synth.pb"
