# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll.xci
# IP: The module: 'ber_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll.xci
# IP: The module: 'ber_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_pll/ber_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
