# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_2/H2_2.xci
# IP: The module: 'H2_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_2/H2_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'H2_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_2/H2_2.xci
# IP: The module: 'H2_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/H2_2/H2_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'H2_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
