######################################################################
#
# File name : encode_TB_wave.do
# Created on: Tue Apr 09 14:53:57 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
