######################################################################
#
# File name : encode_TB_simulate.do
# Created on: Wed Apr 10 17:30:59 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L blk_mem_gen_v8_4_1 -L fifo_generator_v13_2_1 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.encode_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {encode_TB_wave.do}

view wave
view structure
view signals

do {encode_TB.udo}

run 1000ns
