######################################################################
#
# File name : encode_TB_compile.do
# Created on: Wed Apr 10 17:30:57 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelsim\\win64\\vlib modelsim_lib/work
D:\\modelsim\\win64\\vlib modelsim_lib/msim

D:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../encode_ex.srcs/sources_1/ip/clk_wiz_0" \
"../../../../encode_ex.srcs/sources_1/ip/ila_0/sim/ila_0.v" \
"../../../../encode_ex.srcs/sources_1/ip/ila_1/sim/ila_1.v" \
"../../../../encode_ex.srcs/sources_1/ip/H4/sim/H4.v" \
"../../../../encode_ex.srcs/sources_1/ip/H3/sim/H3.v" \
"../../../../encode_ex.srcs/sources_1/ip/H2/sim/H2.v" \
"../../../../encode_ex.srcs/sources_1/ip/H1/sim/H1.v" \
"../../../../encode_ex.srcs/sources_1/ip/rd_fifo/sim/rd_fifo.v" \
"../../../../encode_ex.srcs/sources_1/ip/wr_fifo/sim/wr_fifo.v" \
"../../../../encode_ex.srcs/sources_1/ip/fifo_generator_0/sim/fifo_generator_0.v" \
"../../../../encode_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../encode_ex.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../encode_ex.srcs/sources_1/ip/encode/encode/example_design/encode_tx_startup_fsm.v" \
"../../../../encode_ex.srcs/sources_1/ip/encode/encode/example_design/encode_rx_startup_fsm.v" \
"../../../../encode_ex.srcs/sources_1/ip/encode/encode_init.v" \
"../../../../encode_ex.srcs/sources_1/ip/encode/encode_cpll_railing.v" \
"../../../../encode_ex.srcs/sources_1/ip/encode/encode_gt.v" \
"../../../../encode_ex.srcs/sources_1/ip/encode/encode_multi_gt.v" \
"../../../../encode_ex.srcs/sources_1/ip/encode/encode/example_design/encode_sync_block.v" \
"../../../../encode_ex.srcs/sources_1/ip/encode/encode.v" \
"../../../../encode_ex.srcs/sources_1/imports/example_design/support/encode_common.v" \
"../../../../encode_ex.srcs/sources_1/imports/example_design/support/encode_common_reset.v" \
"../../../../encode_ex.srcs/sources_1/imports/example_design/encode_exdes.v" \
"../../../../encode_ex.srcs/sources_1/imports/example_design/encode_gt_frame_gen.v" \
"../../../../encode_ex.srcs/sources_1/imports/example_design/support/encode_gt_usrclk_source.v" \
"../../../../encode_ex.srcs/sources_1/new/encode_p.v" \
"../../../../encode_ex.srcs/sources_1/imports/example_design/support/encode_support.v" \
"../../../../encode_ex.srcs/sources_1/new/fifo_control.v" \
"../../../../encode_ex.srcs/sources_1/new/ldpc_control.v" \
"../../../../encode_ex.srcs/sim_1/imports/simulation/encode_tb.v" \


# compile glbl module
D:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

