# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/data_pri/data_pri.xci
# IP: The module: 'data_pri' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/data_pri/data_pri_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_pri'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/data_pri/data_pri.xci
# IP: The module: 'data_pri' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/data_pri/data_pri_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_pri'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
