# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_ila/ber_ila.xci
# IP: The module: 'ber_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_ila'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_ila/ber_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_ila/ber_ila.xci
# IP: The module: 'ber_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/doinc/Desktop/decode_final_test/ldpc_5_v2/test_ldpc.srcs/sources_1/ip/ber_ila/ber_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ber_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
