# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/decode/decode.xci
# IP: The module: 'decode' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/decode/decode.xdc
# XDC: The top module name and the constraint reference have the same name: 'decode'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/decode/decode_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'decode'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/decode/decode.xci
# IP: The module: 'decode' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/decode/decode.xdc
# XDC: The top module name and the constraint reference have the same name: 'decode'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/ldpc_5_v2_ber_test/test_ldpc.srcs/sources_1/ip/decode/decode_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'decode'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
